version: "3.7"
services:
  php:
    build:
      context: docker/php
      target: ${ENVIRONMENT:-production-pseudo}
    volumes:
      - .:/app

  nginx:
    build:
      context: docker/nginx
      target: ${ENVIRONMENT:-production-pseudo}
    ports:
      - 8080:80
    volumes:
      - .:/app